cloudApp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('myCloud/',include('myCloud.urls')),
    path("admin/", admin.site.urls),
]

myCloud/urls.py
from django.urls import path, re_path
from . import views
app_name = 'myCloud'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('signUp/', views.signUp, name='signUp'),
    path('home/', views.home, name='home'),
    path('logout/', views.logout, name='logout'),
    path('musics/', views.musics, name='musics'),
    path('query/', views.query, name='query'),
    path('subscription/', views.subscription, name='subscription'),

]

myCloud/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.sessions.backends.base import *
from django.core.paginator import Paginator
import json
import requests
import boto3
import os
from dotenv import load_dotenv
load_dotenv()


def restructureData(songs, names):
    '''This function will generate a list based on the format of Django 
    pagination from songs dictionary and songs' names list'''
    final_data = []
    for i in range(len(songs)):
        tmp_data = {
        }
        tmp_data['title'] = names[i].replace("_", " ")
        tmp_data['year'] = songs[names[i]]['Year']
        tmp_data['artist'] = songs[names[i]]['Artist']
        final_data.append(tmp_data)

    return final_data


def apiGateWay(email, password):
    '''Calling the api to login and get Session for user '''
    url = 'https://xwjymmmd28.execute-api.us-east-1.amazonaws.com/rmit/?student=' + email
    headers = {
        "Content-Type": "application/json"}
    response = requests.get(url, headers=headers)
    data = response.text
    parse_json = json.loads(data)
    if not parse_json:
        return False
    if(parse_json[0]['email'] == email and parse_json[0]['password'] == password):
        user_name = parse_json[0]['user_name']
        return user_name
    return False


def index(request):
    '''Index page view'''
    if 'user' in request.session:
        return redirect('home/')
    else:
        return render(request, 'myCloud/index.html')


def login(request):
    '''Login page view'''
    if 'user' in request.session:
        return redirect('/myCloud/home/')
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('pw')
        user_name = apiGateWay(email, password)
        if (user_name != False):
            request.session['user_email'] = email
            request.session['user'] = user_name
            return redirect('/myCloud/home/', {'current_user': user_name})
        else:
            return render(request, 'myCloud/login.html',
                          {"message": "Email or password is invalid"})
    return render(request, 'myCloud/login.html')


def signUp(request):
    '''Signup page view'''
    if request.method == 'POST':
        user_name = request.POST.get('user_name')
        email = request.POST.get('email')
        password = request.POST.get('pw')
        data = {
            "cloudUser": email,
            "email": email,
            "user_name": user_name,
            "password": password
        }
        url = 'https://xwjymmmd28.execute-api.us-east-1.amazonaws.com/signup/createaccount'
        response = requests.post(url, json=data)
        announcement = response.json()
        return render(request, 'myCloud/signUp.html', {'announcement': announcement['body']})
    return render(request, 'myCloud/signUp.html')


def home(request):
    '''Home page view'''
    if 'user' not in request.session:
        return redirect('/myCloud/')
    else:
        current_user = request.session['user']
        return render(request, 'myCloud/home.html', {'current_user': current_user})


def logout(request):
    '''Logout feature'''
    try:
        # This will delete the session values
        request.session.flush()
    except:
        return redirect('/login/')
    return redirect('/myCloud/login/')


def addingSong(data, user_email):
    '''Function that trigger API to add song to subscription list for the user'''
    title = data['title']
    year = data['year']
    url = 'https://qd7wgwpns8.execute-api.us-east-1.amazonaws.com/updateSubscription/'
    # now  we will call an api with the attribute song thereby interacting and add it into the users vaforite map
    response = requests.post(url, json={
        "song": title,
        "user_email": user_email,
        "year": year
    })
    return response


def musics(request):
    '''Function calling API to retrieve music from the music table
    Instead of searching from the query section the user can view everything and 
    select subscribe'''
    # Note that this is my additional feature; However, the hosted website got errors,
    # So this can be ignored
    if 'user' not in request.session:
        return redirect('/myCloud/login')
    else:
        if request.method == 'POST':
            data = json.loads(request.POST.get('song'))
            user_email = request.session['user_email']
            addingSong(data, user_email)
        dynamodb = boto3.resource('dynamodb')
        table = dynamodb.Table('music')
        data = [table.scan()][0]['Items']

        paginator = Paginator(data, 50)
        page_number = request.GET.get('page')
        page_object = paginator.get_page(page_number)

        current_user = request.session['user']
        return render(request, 'myCloud/musics.html', {
            'songs': page_object,
            'current_user': current_user
        })


def subscription(request):
    '''Subscription view'''
    if 'user' not in request.session:
        return redirect('/myCloud/login/')
    if request.method == 'POST':
        # Removing songs
        song_title = json.loads(request.POST.get('song'))['title']
        user_email = request.session['user_email']
        url = 'https://u1gz12fny5.execute-api.us-east-1.amazonaws.com/removeSong/'
        response = requests.post(url, json={
            "songTitle": song_title.replace(" ", "_"),
            "userEmail": user_email
        })

    user = request.session['user_email']
    url = 'https://xwjymmmd28.execute-api.us-east-1.amazonaws.com/rmit/?student='+user

    headers = {
        "Content-Type": "application/json"}
    response = requests.get(url, headers=headers)
    data = response.text
    parse_json = json.loads(data)
    subscription = parse_json[0]['subscription']
    # Restructuring the fetched values to create a list of json variables
    final_data = restructureData(subscription, list(subscription))
    # After fetching for all the in the subscription section of the user and parse it to final_data,
    # Django paginator will display it
    paginator = Paginator(final_data, 10)
    page_number = request.GET.get('page')
    page_object = paginator.get_page(page_number)
    current_user = request.session['user']

    return render(request, "myCloud/subscription.html", {
        'songs': page_object,
        'current_user': current_user})


def query(request):
    '''Query view'''
    if 'user' not in request.session:
        return redirect('/myCloud/login/')
    current_user = request.session['user']
    if request.method == 'POST':
        # When the user is press the query button
        if 'query' in request.POST:
            title = request.POST.get('title')
            year = request.POST.get('year')
            artist = request.POST.get('artist')
            data = {
                "title": title,
                "year": year,
                "artist": artist
            }
            url = 'https://118tvo0o7g.execute-api.us-east-1.amazonaws.com/querying'
            response = requests.post(url, json=data)

            value = response.text
            song = json.loads(value)['body']

            # If the song is valid it will return a list
            if (type(song) == list):
                paginator = Paginator(song, 50)
                page_number = request.GET.get('page')
                # using Django paginator to display data into to front-end
                page_object = paginator.get_page(page_number)
                return render(request, "myCloud/query.html", {
                    "current_user": current_user,
                    "songs": page_object,
                })
            # else only return a message that the song does not exist
            return render(request, "myCloud/query.html", {
                "current_user": current_user,
                "mess": song
            })
        # When the user press subscribe
        else:
            data = json.loads(request.POST.get('song'))
            user_email = request.session['user_email']
            response_data = addingSong(data, user_email)
            return render(request, "myCloud/query.html", {
                "current_user": current_user,
                "mess": json.loads(response_data.text)['body']
            })
    return render(request, "myCloud/query.html", {
        "current_user": current_user
    })

myCloud/templates/myCloud/home.html
{% extends 'myCloud/index.html' %}
{% block content %}<h1>{{ current_user }}</h1>{% endblock %}

myCloud/templates/myCloud/index.html
<!DOCTYPE html>
<html>
    <head>
   
        <link type="text/css"  rel="stylesheet" href="/static/css/style.css">
    </head>
    <body>
        <nav>
            <div class="nav-link" id="navlink">
                <ul>
                    <li class="nav-button">
                        <a href="{% url 'myCloud:home' %}">MyCloud</a>
                    </li>
                    {% if current_user %}
                        <li>
                            <a href="{% url 'myCloud:musics' %}">Musics</a>
                        </li>
                        <li>
                            <a href="{% url 'myCloud:subscription' %}">Subscription</a>
                        </li>
                        <li>
                            <a href="{% url 'myCloud:query' %}">Query</a>
                        </li>
                        <li>
                            <a href="{% url 'myCloud:logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'myCloud:login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'myCloud:signUp' %}">Sign Up</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        {% block content %}<h1>Welcome to MyCloud</h1>{% endblock %}
    </body>
    {% block feature %}{% endblock %}
</html>

myCloud/templates/myCloud/login.html
{% extends 'myCloud/index.html' %}
{% block content %}
    <h1>Login form</h1>
    <h2>{{ message }}</h2>
    <form method="POST">
        {% csrf_token %}
        <label for="email">Email:</label>
        <br>
        <input type="email" id="email" name="email">
        <br>
        <label for="pw">Password:</label>
        <br>
        <input type="password" id="pw" name="pw">
        <br>
        <input class="button" type="submit" name="login" value="login">
    </form>
{% endblock %}

myCloud/templates/myCloud/musics.html
{% extends 'myCloud/index.html' %}
{% block content %}
    <h1>Songs List</h1>
    <h1>{{ bucket }}</h1>
    <table>
        <tr>
            <th>Picture</th>
            <th>Artist</th>
            <th>Title</th>
            <th>Subcribe</th>
        </tr>
        {% for song in songs %}
            <tr>
                <td id="testing">
                    <img class="song-image" src="{{ song.img_url }}" id="{{ song.artist }}"  />
                </td>
                <td id="artist"  value="{{ song.artist }}">{{ song.artist }}</td>
                <td>{{ song.title }}</td>
                <td>
                    <form method = "POST">
                        {% csrf_token %}
                        <button type="submit"
                                name="song"
                                value='{ "title": "{{ song.title }}", "year": "{{ song.year }}" }'>Subcribe</button>
                    </form>
                </td>
            </tr>
        {% endfor %}
    </table>
    <nav>
        <ul >
            <li >
                <a onclick="" href="?page=1">First</a>
            </li>
            <li >
                {% if songs.has_previous %}
                    <a onclick=""
                       href="?page={{ songs.previous_page_number }}"
                       aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                {% endif %}
            </li>
            {% for i in songs.paginator.page_range %}
                <li >
                    <a onclick=""  href="?page={{i}}">{{i }}</a>
                </li>
            {% endfor %}
            <li >
                {% if songs.has_next %}
                    <a onclick=""
                       href="?page={{ songs.next_page_number }}"
                       aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                {% endif %}
            </li>
            <li>
                <a onclick="" href="?page={{ songs.paginator.num_pages }}">Last</a>
            </li>
        </ul>
    </nav>
{% endblock %}
{% block feature %}{% endblock %}

myCloud/templates/myCloud/query.html
{% extends 'myCloud/musics.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        <label for="title">Title</label>
        <br>
        <input type="text" id="title" name="title">
        <br>
        <label for="year">Year</label>
        <br>
        <input type="text" id="year" name="year">
        <br>
        <label for="artist">Artist</label>
        <br>
        <input type="text" id="artist" name="artist">
        <br>
        <button name="query" type="submit">Find</button>
    </form>
    <table>
        <tr>
            <th>Picture</th>
            <th>Artist</th>
            <th>Title</th>
            <th>Year</th>
            <th>Subcribe</th>
        </tr>
        <h1>{{ mess }}</h1>
        {% for song in songs %}
            <tr>
                <td id="testing">
                    <img class="song-image" src="{{ song.img_url }}" id="{{ song.artist }}"  />
                </td>
                <td id="artist"  value="{{ song.artist }}">{{ song.artist }}</td>
                <td>{{ song.title }}</td>
                <td>{{ song.year }}</td>
                <td>
                    <form method = "POST">
                        {% csrf_token %}
                        <button type="submit"
                                name="song"
                                value='{ "title": "{{ song.title }}", "year": "{{ song.year }}" }'>Subcribe</button>
                    </form>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}
{% block feature %}{% endblock %}

myCloud/templates/myCloud/signUp.html
{% extends 'myCloud/index.html' %}
{% block content %}
    <h1>SignUp form</h1>
    <h2>{{ announcement }}</h2>
    <form method="POST">
        {% csrf_token %}
        <label for="email">Email:</label>
        <br>
        <input type="email" id="email" name="email">
        <br>
        <label for="user_name">User name:</label>
        <br>
        <input type="text" id="user_name" name="user_name">
        <br>
        <label for="pw">Password:</label>
        <br>
        <input type="password" id="pw" name="pw">
        <br>
        <input class="button" type="submit" name="Register" value="Register">
    </form>
{% endblock %}

myCloud/templates/myCloud/subscription.html
{% extends 'myCloud/musics.html' %}
{% block content %}
    <table>
        <tr>
            <th>Picture</th>
            <th>Artist</th>
            <th>Title</th>
            <th>Year</th>
            <th>Remove</th>
        </tr>
        {% for song in songs %}
            <tr>
                <td id="testing">
                    <img class="song-image"  id="{{ song.artist }}"  />
                </td>
                <td id="artist"  value="{{ song.artist }}">{{ song.artist }}</td>
                <td>{{ song.title }}</td>
                <td>{{ song.year }}</td>
                <td>
                    <form method = "POST">
                        {% csrf_token %}
                        <button type="submit"
                                name="song"
                                value='{ "title": "{{ song.title }}", "year": "{{ song.year }}" }'>Remove</button>
                    </form>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}
{% block feature %}
    <script>
	async function fetchImg() {
		const images = document.querySelectorAll('.song-image');
		images.forEach(image => {
			const title = image.getAttribute('id');
			const url = `https://xwjymmmd28.execute-api.us-east-1.amazonaws.com/getSongs/subscribe?artist=${encodeURIComponent(title)}`;
			fetch(url, { mode: 'cors' })
				.then(response => {
					if (response.ok) {
						return response.body;
					}
					throw new Error('Network response was not ok');
				})
				.then(body => {
					const reader = body.getReader();
					const stream = new ReadableStream({
						start(controller) {
							function push() {
								reader.read().then(({ done, value }) => {
									if (done) {
										controller.close();
										return;
									}
									controller.enqueue(value);
									push();
								});
							}
							push();
						}
					});
					return new Response(stream, { headers: { "Content-Type": "text/html" } })
						.text();
				})
				.then(url => {
					image.src = url;
				})
				.catch(error => console.error(error));
		});
	}
	window.onload = fetchImg()
    </script>
{% endblock %}